################################################################################################
#
# Shotgun Pipeline Toolkit Default VFX Configuration
#

description: Apps and Engines showing when an engine is launched with a project only context.

#################################################################################################
# include common definitions for all the launchers that are used to start maya, nuke etc.

includes: [./includes/app_launchers.yml, ./includes/proxy_apps.yml]


#################################################################################################
# define all the items that should appear in this environment 

engines:

  tk-3dsmax:
    apps: '@default_proxy_apps'
    debug_logging: false
    location: {name: tk-3dsmax, type: app_store, version: v0.2.10}
    
  tk-hiero:
    apps:
      tk-hiero-export:
        default_task_template: Basic shot template
        hook_translate_template: default
        location: {name: tk-hiero-export, type: app_store, version: v0.1.2}
        template_nuke_script_path: hiero_nuke_script_path
        template_plate_path: hiero_plate_path
        template_render_path: hiero_render_path
      tk-hiero-openinshotgun:
        location: {name: tk-hiero-openinshotgun, type: app_store, version: v0.1.0}
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.12}
      tk-multi-publish:
        display_name: Publish Project
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.11}
        primary_description: Publish and version up the selected Hiero project
        primary_display_name: Hiero Publish
        primary_icon: icons/publish_hiero_main.png
        primary_publish_template: hiero_project_publish
        primary_scene_item_type: work_file
        primary_tank_type: Hiero Project
        secondary_outputs: []
        template_work: hiero_project_work
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.10}
        template_snapshot: hiero_project_snapshot
        template_work: hiero_project_work
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_scene_operation: default
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.23}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_filters: {}
        sg_entity_types: []
        template_publish: hiero_project_publish
        template_publish_area: hiero_project_publish_area
        template_work: hiero_project_work
        template_work_area: hiero_project_work_area
    bin_context_menu:
    - {app_instance: tk-multi-workfiles, keep_in_menu: false, name: Shotgun Save As...,
      requires_selection: true}
    - {app_instance: tk-multi-workfiles, keep_in_menu: false, name: Version up Current
        Scene..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot History...,
      requires_selection: true}
    - {app_instance: tk-multi-publish, keep_in_menu: false, name: Publish Project...,
      requires_selection: true}
    debug_logging: false
    location: {name: tk-hiero, type: app_store, version: v0.2.1}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    spreadsheet_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
    timeline_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
      
  tk-maya:
    apps: '@default_proxy_apps'
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.3.7}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    use_sgtk_as_menu_name: false
    
  tk-nuke:
    apps: '@default_proxy_apps'
    debug_logging: false
    location: {name: tk-nuke, type: app_store, version: v0.2.13}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    use_sgtk_as_menu_name: false
    
  tk-photoshop:
    apps: '@default_proxy_apps'
    debug_logging: false
    location: {name: tk-photoshop, type: app_store, version: v0.1.5}
    
  tk-shell:
    apps: 
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchhiero: '@launch_hiero'
      tk-shotgun-launchphotoshop: '@launch_photoshop'    
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.3}
    
  tk-softimage:
    apps: '@default_proxy_apps'
    debug_logging: false
    location: {name: tk-softimage, type: app_store, version: v0.2.2}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    
frameworks:
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
