################################################################################################
#
# Tank Default VFX Configuration
#

description: Apps and Engines showing when an engine is launched with a project only context.

#################################################################################################
# include common definitions for all the launchers that are used to start maya, nuke etc.

include: ./includes/app_launchers.yml


#################################################################################################
# define all the items that should appear in this environment 

engines:

  tk-shell:
    apps: 
    
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchmotionbuilder: '@launch_motionbuilder'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshop: '@launch_photoshop'      
      tk-multi-screeningroom: '@launch_screeningroom'
    
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.6}

    debug_logging: false
    location: {name: tk-shell, type: dev, path: /Users/manne/git/tk-shell}


  tk-3dsmax:
    apps:
      tk-multi-workfiles:
        location: {name: tk-multi-workfiles, type: app_store, version: v0.2.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
        hook_copy_file: default
        hook_scene_operation: default    
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.6}
    debug_logging: false
    location: {name: tk-3dsmax, type: app_store, version: v0.2.4}


  tk-maya:
    apps:
      tk-multi-workfiles:
        location: {name: tk-multi-workfiles, type: app_store, version: v0.2.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
        hook_copy_file: default
        hook_scene_operation: default    
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.6}

    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.2.5}
    menu_favourites:
    - {app_instance: tk-multi-recentfiles, name: Recent Work Files...}
    - {app_instance: tk-maya-publish, name: Snapshot}
    - {app_instance: tk-maya-publish, name: Publish...}
    template_project: shot_work_area_maya


  tk-motionbuilder:
    apps:
      tk-multi-workfiles:
        location: {name: tk-multi-workfiles, type: app_store, version: v0.2.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
        hook_copy_file: default
        hook_scene_operation: default    
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.6}

    debug_logging: false
    location: {name: tk-motionbuilder, type: app_store, version: v0.2.6}
    menu_favourites:
    - {app_instance: tk-multi-recentfiles, name: Recent Work Files...}
    - {app_instance: tk-motionbuilder-publish, name: Snapshot}
    - {app_instance: tk-motionbuilder-publish, name: Publish...}


  tk-nuke:
    apps:
      tk-multi-workfiles:
        location: {name: tk-multi-workfiles, type: app_store, version: v0.2.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
        hook_copy_file: default
        hook_scene_operation: default    
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.6}

    debug_logging: false
    location: {name: tk-nuke, type: app_store, version: v0.2.10}
    menu_favourites:
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Tank File Manager...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles, name: Tank Save As...}
    - {app_instance: tk-multi-publish, name: Publish...}
    - {app_instance: tk-nuke-review, name: Submit for Review...}


  tk-photoshop:
    apps:
      tk-multi-workfiles:
        location: {name: tk-multi-workfiles, type: app_store, version: v0.2.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
        hook_copy_file: default
        hook_scene_operation: default    
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.6}

    debug_logging: true
    location: {name: tk-photoshop, type: app_store, version: v0.0.12}


frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
